package com.stream.utils.impl;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Objects;

import com.stream.utils.Tuple;
import com.utils.ObjectUtils;

/**
 * An immutable pair consisting of two elements.
 * <p>
 * This implementation refers to the elements as 'first' and 'second'.
 * The elements cannot be null.
 * <p>
 * Although the implementation is immutable, there is no restriction on the objects
 * that may be stored. If mutable objects are stored in the pair, then the pair itself
 * effectively becomes mutable.
 * <p>
 * Some primitive specializations of this class are provided, such as {@link DoublesPair}.
 * <p>
 * This class is immutable and thread-safe if the stored objects are immutable.
 *
 * @param <A> the first element type
 * @param <B> the second element type
 */

public final class Pair<A, B>
    implements Tuple, Comparable<Pair<A, B>>, Serializable {

  /**
   * The first element in this pair.
   */
  private final A first;
  /**
   * The second element in this pair.
   */
  private final B second;

  //-------------------------------------------------------------------------
  /**
   * Obtains a pair inferring the types.
   * 
   * @param <A> the first element type
   * @param <B> the second element type
   * @param first  the first element
   * @param second  the second element
   * @return a pair formed from the two parameters
   */
  public static <A, B> Pair<A, B> of(A first, B second) {
    return new Pair<>(first, second);
  }

  //-------------------------------------------------------------------------
  /**
   * Gets the number of elements held by this pair.
   * 
   * @return size 2
   */
  @Override
  public int size() {
    return 2;
  }

  /**
   * Gets the elements from this pair as a list.
   * <p>
   * The list returns each element in the pair in order.
   * 
   * @return the elements as an immutable list
   */
  @Override
  public List<Object> elements() {
	  ArrayList<Object> list = new ArrayList<>(2);
	  list.add(first);
	  list.add(second);
	  return Collections.unmodifiableList(list);
  }

  //-------------------------------------------------------------------------
  /**
   * Compares the pair based on the first element followed by the second element.
   * <p>
   * The element types must be {@code Comparable}.
   * 
   * @param other  the other pair
   * @return negative if this is less, zero if equal, positive if greater
   * @throws ClassCastException if either object is not comparable
   */
  @Override
  public int compareTo(Pair<A, B> other) {
    return ComparisonChain.start()
        .compare((Comparable<?>) first, (Comparable<?>) other.first)
        .compare((Comparable<?>) second, (Comparable<?>) other.second)
        .result();
  }

  /**
   * Gets the pair using a standard string format.
   * <p>
   * The standard format is '[$first, $second]'. Spaces around the values are trimmed.
   * 
   * @return the pair as a string
   */
  @Override
  public String toString() {
    return new StringBuilder()
        .append('[')
        .append(first)
        .append(", ")
        .append(second)
        .append(']')
        .toString();
  }

  //------------------------- AUTOGENERATED START -------------------------



  /**
   * The serialization version id.
   */
  private static final long serialVersionUID = 1L;

  private Pair(
      A first,
      B second) {
	  ObjectUtils.notNull(first, "first");
	  ObjectUtils.notNull(second, "second");
	  this.first = first;
	  this.second = second;
  }


  //-----------------------------------------------------------------------
  /**
   * Gets the first element in this pair.
   * @return the value of the property, not null
   */
  public A getFirst() {
    return first;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the second element in this pair.
   * @return the value of the property, not null
   */
  public B getSecond() {
    return second;
  }

  //-----------------------------------------------------------------------
  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      Pair<?, ?> other = (Pair<?, ?>) obj;
      return ObjectUtils.equal(first, other.first) &&
    		  ObjectUtils.equal(second, other.second);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + Objects.hashCode(first);
    hash = hash * 31 + Objects.hashCode(second);
    return hash;
  }

  //-----------------------------------------------------------------------

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code Pair}.
   * @param <A>  the type
   * @param <B>  the type
   */
  private static final class Builder<A, B>  {

    private A first;
    private B second;

    /**
     * Restricted constructor.
     */
    private Builder() {
    }

    //-----------------------------------------------------------------------
    @SuppressWarnings("unused")
	public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case 97440432:  // first
          return first;
        case -906279820:  // second
          return second;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @SuppressWarnings("unchecked")
    public Builder<A, B> set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case 97440432:  // first
          this.first = (A) newValue;
          break;
        case -906279820:  // second
          this.second = (B) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }


    public Pair<A, B> build() {
      return new Pair<>(
          first,
          second);
    }


    public String toString() {
      StringBuilder buf = new StringBuilder(96);
      buf.append("Pair.Builder{");
      buf.append("first").append('=').append(ObjectUtils.toString(first)).append(',').append(' ');
      buf.append("second").append('=').append(ObjectUtils.toString(second));
      buf.append('}');
      return buf.toString();
    }

  }
}